REM v0.0.0.3
REM This file was auto-generated by PowerZero at 09/04/2016 02:17:28
"C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" "ODataSample.Web.xproj" /t:Rebuild /p:TargetProfile=Local 
pause
