#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.WebPages.Administration.PackageManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/packages/_Layout.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0.0.0")]
    public class packages__Layout_cshtml : System.Web.WebPages.WebPage
    {
#line hidden

                    // Resolve package relative syntax
                    // Also, if it comes from a static embedded resource, change the path accordingly
                    public override string Href(string virtualPath, params object[] pathParts) {
                        virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                        return base.Href(virtualPath, pathParts);
                    }
        public packages__Layout_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


  
    Layout = "../_Layout.cshtml";
    Page.Title = PackageManagerResources.ModuleTitle;



DefineSection("Head", () => {

WriteLiteral("\r\n    <link href=\"");


           Write(Href("Site.css"));

WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"http://ajax.microsoft.com" +
"/ajax/jquery/jquery-1.4.2.js\" type=\"text/javascript\"></script>\r\n\r\n    ");


Write(RenderSection("PackageHead", required: false));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("PageSettings", () => {

WriteLiteral("\r\n    <a href=\"");


        Write(Href("PackageSources"));

WriteLiteral("\">");


                                 Write(PackageManagerResources.ManageSourcesTitle);

WriteLiteral("</a>\r\n");


});

WriteLiteral("\r\n\r\n");


Write(RenderBody());

WriteLiteral("\r\n\r\n");


DefineSection("Footer", () => {

WriteLiteral("\r\n    <a href=\"http://go.microsoft.com/fwlink/?LinkID=205205\" target=\"_blank\">");


                                                                       Write(PackageManagerResources.PrivacyStatement);

WriteLiteral("</a>\r\n");


});


        }
    }
}
#pragma warning restore 1591
