//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Http.Cors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Http.Cors.Properties.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Access-Control-Request-Method&quot; header value cannot be null or empty..
        /// </summary>
        internal static string AccessControlRequestMethodCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("AccessControlRequestMethodCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or an empty string..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Access-Control-Request-Method&quot; header value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidAccessControlRequestMethod {
            get {
                return ResourceManager.GetString("InvalidAccessControlRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request does not have an associated configuration object..
        /// </summary>
        internal static string NoConfiguration {
            get {
                return ResourceManager.GetString("NoConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified policy origin cannot be null or empty..
        /// </summary>
        internal static string OriginCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("OriginCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified policy origin &apos;{0}&apos; is invalid. It cannot end with a forward slash..
        /// </summary>
        internal static string OriginCannotEndWithSlash {
            get {
                return ResourceManager.GetString("OriginCannotEndWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified policy origin &apos;{0}&apos; is invalid. It must not contain a path, query, or fragment..
        /// </summary>
        internal static string OriginMustNotContainPathQueryOrFragment {
            get {
                return ResourceManager.GetString("OriginMustNotContainPathQueryOrFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified policy origin &apos;{0}&apos; is invalid. It must be correctly formed with the scheme, the host, and optionally, the port..
        /// </summary>
        internal static string OriginNotWellFormed {
            get {
                return ResourceManager.GetString("OriginNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorsRequestContext: &apos;{0}&apos;.
        /// </summary>
        internal static string TraceCorsRequestContext {
            get {
                return ResourceManager.GetString("TraceCorsRequestContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorsResult returned: &apos;{0}&apos;.
        /// </summary>
        internal static string TraceEndCorsResultReturned {
            get {
                return ResourceManager.GetString("TraceEndCorsResultReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CorsResult returned..
        /// </summary>
        internal static string TraceEndNoCorsResultReturned {
            get {
                return ResourceManager.GetString("TraceEndNoCorsResultReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CorsPolicyProvider selected.
        /// </summary>
        internal static string TraceEndNoPolicyProviderReturned {
            get {
                return ResourceManager.GetString("TraceEndNoPolicyProviderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CorsPolicy selected.
        /// </summary>
        internal static string TraceEndNoPolicyReturned {
            get {
                return ResourceManager.GetString("TraceEndNoPolicyReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorsPolicyProvider selected: &apos;{0}&apos;.
        /// </summary>
        internal static string TraceEndPolicyProviderReturned {
            get {
                return ResourceManager.GetString("TraceEndPolicyProviderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorsPolicy selected: &apos;{0}&apos;.
        /// </summary>
        internal static string TraceEndPolicyReturned {
            get {
                return ResourceManager.GetString("TraceEndPolicyReturned", resourceCulture);
            }
        }
    }
}
