//-----------------------------------------------------------------------------
// <copyright file="ComplexTypeInheritance.cs" company=".NET Foundation">
//      Copyright (c) .NET Foundation and Contributors. All rights reserved. 
//      See License.txt in the project root for license information.
// </copyright>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 7/14/2014 3:46:34 PM
namespace Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance", "Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.", clientType.Name);
            }
            if (originalNameAttribute != null)
            {
                return clientType.Namespace + "." + originalNameAttribute.OriginalName;
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Windows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Window> Windows
        {
            get
            {
                if ((this._Windows == null))
                {
                    this._Windows = base.CreateQuery<Window>("Windows");
                }
                return this._Windows;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Window> _Windows;
        /// <summary>
        /// There are no comments for Windows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToWindows(Window window)
        {
            base.AddObject("Windows", window);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:Runtime>
    <edmx:ConceptualModels>
      <Schema Namespace=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
        <EntityType Name=""Window"">
          <Key>
            <PropertyRef Name=""Id"" />
          </Key>
          <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
          <Property Name=""Name"" Type=""Edm.String"" />
          <Property Name=""CurrentShape"" Type=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Shape"" />
          <Property Name=""OptionalShapes"" Type=""Collection(Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Shape)"" />
          <NavigationProperty Name=""Parent"" Type=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Window"" />
        </EntityType>
        <ComplexType Name=""Shape"" Abstract=""true"">
          <Property Name=""HasBorder"" Type=""Edm.Boolean"" Nullable=""false"" />
        </ComplexType>
        <ComplexType Name=""Polygon"" BaseType=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Shape"">
          <Property Name=""Vertexes"" Type=""Collection(Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Point)"" />
        </ComplexType>
        <ComplexType Name=""Rectangle"" BaseType=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Polygon"">
          <Property Name=""TopLeft"" Type=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Point"" />
          <Property Name=""Width"" Type=""Edm.Int32"" Nullable=""false"" />
          <Property Name=""Height"" Type=""Edm.Int32"" Nullable=""false"" />
        </ComplexType>
        <ComplexType Name=""Point"">
          <Property Name=""X"" Type=""Edm.Int32"" Nullable=""false"" />
          <Property Name=""Y"" Type=""Edm.Int32"" Nullable=""false"" />
        </ComplexType>
        <ComplexType Name=""Circle"" BaseType=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Shape"">
          <Property Name=""Center"" Type=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Point"" />
          <Property Name=""Radius"" Type=""Edm.Int32"" Nullable=""false"" />
        </ComplexType>
        <EntityContainer Name=""Container"">
          <EntitySet Name=""Windows"" EntityType=""Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Window"">
            <NavigationPropertyBinding Path=""Parent"" Target=""Windows"" />
          </EntitySet>
        </EntityContainer>
      </Schema>
    </edmx:ConceptualModels>
  </edmx:Runtime>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WindowSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("WindowSingle")]
    public partial class WindowSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Window>
    {
        /// <summary>
        /// Initialize a new WindowSingle object.
        /// </summary>
        public WindowSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new WindowSingle object.
        /// </summary>
        public WindowSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle Parent
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Parent == null))
                {
                    this._Parent = new global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle(this.Context, GetPath("Parent"));
                }
                return this._Parent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle _Parent;
    }
    /// <summary>
    /// There are no comments for Window in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("Windows")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Window")]
    public partial class Window : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Window object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Window CreateWindow(int ID)
        {
            Window window = new Window();
            window.Id = ID;
            return window;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CurrentShape in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentShape")]
        public global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape CurrentShape
        {
            get
            {
                return this._CurrentShape;
            }
            set
            {
                this.OnCurrentShapeChanging(value);
                this._CurrentShape = value;
                this.OnCurrentShapeChanged();
                this.OnPropertyChanged("CurrentShape");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape _CurrentShape;
        partial void OnCurrentShapeChanging(global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape value);
        partial void OnCurrentShapeChanged();
        /// <summary>
        /// There are no comments for Property OptionalShapes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OptionalShapes")]
        public global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape> OptionalShapes
        {
            get
            {
                return this._OptionalShapes;
            }
            set
            {
                this.OnOptionalShapesChanging(value);
                this._OptionalShapes = value;
                this.OnOptionalShapesChanged();
                this.OnPropertyChanged("OptionalShapes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape> _OptionalShapes = new global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape>();
        partial void OnOptionalShapesChanging(global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Shape> value);
        partial void OnOptionalShapesChanged();
        /// <summary>
        /// There are no comments for Property Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Window Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this.OnParentChanging(value);
                this._Parent = value;
                this.OnParentChanged();
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Window _Parent;
        partial void OnParentChanging(global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Window value);
        partial void OnParentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shape in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Shape")]
    public abstract partial class Shape : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property HasBorder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasBorder")]
        public bool HasBorder
        {
            get
            {
                return this._HasBorder;
            }
            set
            {
                this.OnHasBorderChanging(value);
                this._HasBorder = value;
                this.OnHasBorderChanged();
                this.OnPropertyChanged("HasBorder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private bool _HasBorder;
        partial void OnHasBorderChanging(bool value);
        partial void OnHasBorderChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Polygon in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Polygon")]
    public partial class Polygon : Shape
    {
        /// <summary>
        /// Create a new Polygon object.
        /// </summary>
        /// <param name="hasBorder">Initial value of HasBorder.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Polygon CreatePolygon(bool hasBorder)
        {
            Polygon polygon = new Polygon();
            polygon.HasBorder = hasBorder;
            return polygon;
        }
        /// <summary>
        /// There are no comments for Property Vertexes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Vertexes")]
        public global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point> Vertexes
        {
            get
            {
                return this._Vertexes;
            }
            set
            {
                this.OnVertexesChanging(value);
                this._Vertexes = value;
                this.OnVertexesChanged();
                this.OnPropertyChanged("Vertexes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point> _Vertexes = new global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point>();
        partial void OnVertexesChanging(global::System.Collections.ObjectModel.ObservableCollection<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point> value);
        partial void OnVertexesChanged();
    }
    /// <summary>
    /// There are no comments for Rectangle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Rectangle")]
    public partial class Rectangle : Polygon
    {
        /// <summary>
        /// Create a new Rectangle object.
        /// </summary>
        /// <param name="hasBorder">Initial value of HasBorder.</param>
        /// <param name="width">Initial value of Width.</param>
        /// <param name="height">Initial value of Height.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Rectangle CreateRectangle(bool hasBorder, int width, int height)
        {
            Rectangle rectangle = new Rectangle();
            rectangle.HasBorder = hasBorder;
            rectangle.Width = width;
            rectangle.Height = height;
            return rectangle;
        }
        /// <summary>
        /// There are no comments for Property TopLeft in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TopLeft")]
        public global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point TopLeft
        {
            get
            {
                return this._TopLeft;
            }
            set
            {
                this.OnTopLeftChanging(value);
                this._TopLeft = value;
                this.OnTopLeftChanged();
                this.OnPropertyChanged("TopLeft");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point _TopLeft;
        partial void OnTopLeftChanging(global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point value);
        partial void OnTopLeftChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Width")]
        public int Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Width;
        partial void OnWidthChanging(int value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Height")]
        public int Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Height;
        partial void OnHeightChanging(int value);
        partial void OnHeightChanged();
    }
    /// <summary>
    /// There are no comments for Point in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Point")]
    public partial class Point : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Point object.
        /// </summary>
        /// <param name="x">Initial value of X.</param>
        /// <param name="y">Initial value of Y.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Point CreatePoint(int x, int y)
        {
            Point point = new Point();
            point.X = x;
            point.Y = y;
            return point;
        }
        /// <summary>
        /// There are no comments for Property X in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("X")]
        public int X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this._X = value;
                this.OnXChanged();
                this.OnPropertyChanged("X");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _X;
        partial void OnXChanging(int value);
        partial void OnXChanged();
        /// <summary>
        /// There are no comments for Property Y in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Y")]
        public int Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this._Y = value;
                this.OnYChanged();
                this.OnPropertyChanged("Y");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Y;
        partial void OnYChanging(int value);
        partial void OnYChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Circle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Circle")]
    public partial class Circle : Shape
    {
        /// <summary>
        /// Create a new Circle object.
        /// </summary>
        /// <param name="hasBorder">Initial value of HasBorder.</param>
        /// <param name="radius">Initial value of Radius.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Circle CreateCircle(bool hasBorder, int radius)
        {
            Circle circle = new Circle();
            circle.HasBorder = hasBorder;
            circle.Radius = radius;
            return circle;
        }
        /// <summary>
        /// There are no comments for Property Center in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Center")]
        public global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point Center
        {
            get
            {
                return this._Center;
            }
            set
            {
                this.OnCenterChanging(value);
                this._Center = value;
                this.OnCenterChanged();
                this.OnPropertyChanged("Center");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point _Center;
        partial void OnCenterChanging(global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Point value);
        partial void OnCenterChanged();
        /// <summary>
        /// There are no comments for Property Radius in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Radius")]
        public int Radius
        {
            get
            {
                return this._Radius;
            }
            set
            {
                this.OnRadiusChanging(value);
                this._Radius = value;
                this.OnRadiusChanged();
                this.OnPropertyChanged("Radius");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Radius;
        partial void OnRadiusChanging(int value);
        partial void OnRadiusChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods2
    {
        /// <summary>
        /// Get an entity of type global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Window as global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.Window> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Microsoft.Test.E2E.AspNet.OData.ComplexTypeInheritance.Proxy.WindowSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
