// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Controllers", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Models", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NAMESPACE", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NAMESPACE", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Controllers", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NAMESPACE", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Models", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "PROJECT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "PROJECT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Controllers", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "PROJECT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Models", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ROOT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Controllers", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ROOT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Models", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ROOT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Controllers", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.Models", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "config", Scope = "member", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.HelpPageConfig.#Register(System.Web.Http.HttpConfiguration)", Justification = "This parameter is part of the template and could be used later.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "The assembly will not be deployed because we distribute the source code.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Web.FxCop", "MW1201:DoNotCallProblematicMethodsOnTaskRule", Scope = "member", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.HelpPageSampleGenerator.#WriteSampleObjectUsingFormatter(System.Net.Http.Formatting.MediaTypeFormatter,System.Object,System.Type,System.Net.Http.Headers.MediaTypeHeaderValue)", Justification = "This is an internal FxCop rule and we ship the source file.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ROOT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.ModelDescriptions", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.ModelDescriptions", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "PROJECT", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.ModelDescriptions", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NAMESPACE", Scope = "namespace", Target = "ROOT_PROJECT_NAMESPACE.Areas.HelpPage.ModelDescriptions", Justification = "This namespace will be replaced with the project namespace when the help page is installed.")]
