#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.WebPages.Administration
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using System.Globalization;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/EnableInstructions.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0.0.0")]
    public class EnableInstructions_cshtml : System.Web.WebPages.WebPage
    {
#line hidden

                    // Resolve package relative syntax
                    // Also, if it comes from a static embedded resource, change the path accordingly
                    public override string Href(string virtualPath, params object[] pathParts) {
                        virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                        return base.Href(virtualPath, pathParts);
                    }
        public EnableInstructions_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


  
    Page.Title = AdminResources.SecurityTitle;

    if(AdminSecurity.HasAdminPassword()) {
        SiteAdmin.RedirectToHome(Response);
        return;
    }

    string url = SiteAdmin.GetRedirectUrl(SiteAdmin.AdminVirtualPath);
   

WriteLiteral("\r\n");


Write(Html.Raw(AdminResources.EnableInstructions));

WriteLiteral("\r\n<br />\r\n<p>\r\n    ");


Write(Html.Raw(String.Format(CultureInfo.CurrentCulture, AdminResources.ContinueAfterEnableText, Html.Encode(Href(url)))));

WriteLiteral("\r\n</p>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
