//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Http.OData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaselineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaselineResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Http.OData.BaselineResource", typeof(BaselineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/#Collection(Edm.Boolean)&quot;,&quot;value&quot;:[
        ///    true,false,true,false
        ///  ]
        ///}.
        /// </summary>
        internal static string ArrayOfBooleanInJsonLight {
            get {
                return ResourceManager.GetString("ArrayOfBooleanInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Binary&quot;&gt;AAIgQID/&lt;/d:ID&gt;.
        /// </summary>
        internal static string ArrayOfByteInXml {
            get {
                return ResourceManager.GetString("ArrayOfByteInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/#Collection(Edm.Int32)&quot;,&quot;value&quot;:[
        ///    10,20,30,40,50
        ///  ]
        ///}.
        /// </summary>
        internal static string ArrayOfInt32InJsonLight {
            get {
                return ResourceManager.GetString("ArrayOfInt32InJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Boolean&quot;&gt;true&lt;/d:ID&gt;.
        /// </summary>
        internal static string BooleanInXml {
            get {
                return ResourceManager.GetString("BooleanInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Byte&quot;&gt;64&lt;/d:ID&gt;.
        /// </summary>
        internal static string ByteInXml {
            get {
                return ResourceManager.GetString("ByteInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/#Collection(System.Web.Http.OData.TestCommon.Models.Person)&quot;,&quot;value&quot;:[
        ///    {
        ///      &quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Models.Person&quot;,&quot;Age&quot;:20,&quot;Gender&quot;:&quot;Male&quot;,&quot;FirstName&quot;:&quot;Frank&quot;,&quot;Alias&quot;:[
        ///        &quot;Alias0&quot;
        ///      ],&quot;Address&quot;:{
        ///        &quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Models.Address&quot;,&quot;StreetAddress&quot;:&quot;StreetAddress1&quot;,&quot;City&quot;:&quot;City1&quot;,&quot;State&quot;:&quot;State1&quot;,&quot;ZipCode&quot;:1
        ///      },&quot;HomeNumber&quot;:{
        ///        &quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CollectionOfPersonInJsonLight {
            get {
                return ResourceManager.GetString("CollectionOfPersonInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.DateTime&quot;&gt;2010-01-01T00:00:00&lt;/d:ID&gt;.
        /// </summary>
        internal static string DateTimeInXml {
            get {
                return ResourceManager.GetString("DateTimeInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Decimal&quot;&gt;12345.99999&lt;/d:ID&gt;.
        /// </summary>
        internal static string DecimalInXml {
            get {
                return ResourceManager.GetString("DecimalInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Double&quot;&gt;99999.12345&lt;/d:ID&gt;.
        /// </summary>
        internal static string DoubleInXml {
            get {
                return ResourceManager.GetString("DoubleInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/$metadata#Default.Container.employees/@Element&quot;,&quot;odata.id&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;odata.editLink&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;odata.readLink&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;Manager@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/Manager&quot;,&quot;DirectReports@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/DirectReports&quot;,&quot;WorkItem@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/WorkItem&quot;,&quot;EmployeeId@odata.type&quot;:&quot;Edm.Int64&quot;,&quot;Empl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeeEntryInJsonLight {
            get {
                return ResourceManager.GetString("EmployeeEntryInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/$metadata#Default.Container.employees&quot;,&quot;value&quot;:[
        ///    {
        ///      &quot;odata.id&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;odata.editLink&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;odata.readLink&quot;:&quot;http://localhost/employees(0L)&quot;,&quot;Manager@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/Manager&quot;,&quot;DirectReports@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/DirectReports&quot;,&quot;WorkItem@odata.navigationLinkUrl&quot;:&quot;http://localhost/employees(0L)/WorkItem&quot;,&quot;EmployeeId@odata.type&quot;:&quot;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeedOfEmployeeInJsonLight {
            get {
                return ResourceManager.GetString("FeedOfEmployeeInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Guid&quot;&gt;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&lt;/d:ID&gt;.
        /// </summary>
        internal static string GuidInXml {
            get {
                return ResourceManager.GetString("GuidInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Int16&quot;&gt;-32768&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int16InXml {
            get {
                return ResourceManager.GetString("Int16InXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Int32&quot;&gt;-2147483648&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int32InXml {
            get {
                return ResourceManager.GetString("Int32InXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Int64&quot;&gt;-9223372036854775808&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int64InXml {
            get {
                return ResourceManager.GetString("Int64InXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/#Collection(Edm.String)&quot;,&quot;value&quot;:[
        ///    &quot;Frank&quot;,&quot;Steve&quot;,&quot;Tom&quot;,&quot;Chandler&quot;
        ///  ]
        ///}.
        /// </summary>
        internal static string ListOfStringInJsonLight {
            get {
                return ResourceManager.GetString("ListOfStringInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Boolean&quot;&gt;false&lt;/d:ID&gt;.
        /// </summary>
        internal static string NullableBooleanInXml {
            get {
                return ResourceManager.GetString("NullableBooleanInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:null=&quot;true&quot; /&gt;.
        /// </summary>
        internal static string NullableInt32InXml {
            get {
                return ResourceManager.GetString("NullableInt32InXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/#System.Web.Http.OData.TestCommon.Models.Person&quot;,&quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Models.Person&quot;,&quot;Age&quot;:20,&quot;Gender&quot;:&quot;Male&quot;,&quot;FirstName&quot;:&quot;Frank&quot;,&quot;Alias&quot;:[
        ///    &quot;Alias0&quot;
        ///  ],&quot;Address&quot;:{
        ///    &quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Models.Address&quot;,&quot;StreetAddress&quot;:&quot;StreetAddress1&quot;,&quot;City&quot;:&quot;City1&quot;,&quot;State&quot;:&quot;State1&quot;,&quot;ZipCode&quot;:1
        ///  },&quot;HomeNumber&quot;:{
        ///    &quot;odata.type&quot;:&quot;System.Web.Http.OData.TestCommon.Models.PhoneNumber&quot;,&quot;CountryCode&quot;:1,&quot;AreaCode&quot;:425,&quot;Number [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonComplexTypeInJsonLight {
            get {
                return ResourceManager.GetString("PersonComplexTypeInJsonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://localhost:8081/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///  &lt;id&gt;http://localhost:8081/People(10)&lt;/id&gt;
        ///  &lt;category term=&quot;System.Web.Http.OData.Formatter.FormatterPerson&quot; scheme=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/scheme&quot; /&gt;
        ///  &lt;link rel=&quot;edit&quot; href=&quot;http://localhost:8081/People(10)&quot; /&gt;
        ///  &lt;link [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonEntryInAtom {
            get {
                return ResourceManager.GetString("PersonEntryInAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost:8081/$metadata#Default.Container.People/@Element&quot;,&quot;odata.id&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;odata.editLink&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;odata.readLink&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;PerId&quot;:10,&quot;Age&quot;:10,&quot;MyGuid@odata.type&quot;:&quot;Edm.Guid&quot;,&quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,&quot;Name&quot;:&quot;Asha&quot;,&quot;Order&quot;:{
        ///    &quot;odata.type&quot;:&quot;System.Web.Http.OData.Formatter.FormatterOrder&quot;,&quot;OrderAmount&quot;:235342,&quot;OrderName&quot;:&quot;FirstOrder&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string PersonEntryInJsonFullMetadata {
            get {
                return ResourceManager.GetString("PersonEntryInJsonFullMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;d&quot;:{
        ///    &quot;__metadata&quot;:{
        ///      &quot;id&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;uri&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;type&quot;:&quot;System.Web.Http.OData.Formatter.FormatterPerson&quot;
        ///    },&quot;PerId&quot;:10,&quot;Age&quot;:10,&quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,&quot;Name&quot;:&quot;Asha&quot;,&quot;Order&quot;:{
        ///      &quot;__metadata&quot;:{
        ///        &quot;type&quot;:&quot;System.Web.Http.OData.Formatter.FormatterOrder&quot;
        ///      },&quot;OrderAmount&quot;:235342,&quot;OrderName&quot;:&quot;FirstOrder&quot;
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string PersonEntryInJsonVerbose {
            get {
                return ResourceManager.GetString("PersonEntryInJsonVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Age&quot;:10,&quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,&quot;Name&quot;:&quot;Asha&quot;,&quot;Order&quot;:{&quot;OrderAmount&quot;:235342,&quot;OrderName&quot;:&quot;FirstOrder&quot;},&quot;PerId&quot;:10}.
        /// </summary>
        internal static string PersonEntryInPlainOldJson {
            get {
                return ResourceManager.GetString("PersonEntryInPlainOldJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PerId&quot;:10,
        ///  &quot;Age&quot;:10,
        ///  &quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,
        ///  &quot;Name&quot;:&quot;Asha&quot;,
        ///  &quot;Order&quot;:{
        ///    &quot;OrderAmount&quot;:235342,
        ///    &quot;OrderName&quot;:&quot;FirstOrder&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string PersonRequestEntryInPlainOldJson {
            get {
                return ResourceManager.GetString("PersonRequestEntryInPlainOldJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Bread&lt;/title&gt;
        ///  &lt;summary type=&quot;text&quot;&gt;Whole grain bread&lt;/summary&gt;
        ///  &lt;updated&gt;2012-04-19T00:54:33Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;
        ///  &lt;category term=&quot;ODataDemo.Product&quot; scheme=&quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductRequestEntryInAtom {
            get {
                return ResourceManager.GetString("ProductRequestEntryInAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:DataServiceVersion=&quot;2.0&quot;&gt;
        ///    &lt;Schema Namespace=&quot;ODataDemo&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2007/05/edm&quot;&gt;
        ///      &lt;EntityType Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductsCSDL {
            get {
                return ResourceManager.GetString("ProductsCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.SByte&quot;&gt;-128&lt;/d:ID&gt;.
        /// </summary>
        internal static string SByteInXml {
            get {
                return ResourceManager.GetString("SByteInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Single&quot;&gt;INF&lt;/d:ID&gt;.
        /// </summary>
        internal static string SingleInXml {
            get {
                return ResourceManager.GetString("SingleInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;This is a Test String&lt;/d:ID&gt;.
        /// </summary>
        internal static string StringInXml {
            get {
                return ResourceManager.GetString("StringInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:etag=&quot;W/&amp;quot;0&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;id&gt;http://services.odata.org/OData/OData.svc/Suppliers(0)&lt;/id&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Exotic Liquids&lt;/title&gt;
        ///  &lt;updated&gt;2012-04-19T04:30:47Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplierPatchInAtom {
            get {
                return ResourceManager.GetString("SupplierPatchInAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:etag=&quot;W/&amp;quot;0&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;id&gt;http://services.odata.org/OData/OData.svc/Suppliers(0)&lt;/id&gt;
        ///  &lt;title type=&quot;text&quot;&gt;SampleSupplier&lt;/title&gt;
        ///  &lt;updated&gt;2012-04-19T04:30:47Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplierRequestEntryInAtom {
            get {
                return ResourceManager.GetString("SupplierRequestEntryInAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Time&quot;&gt;PT1H&lt;/d:ID&gt;.
        /// </summary>
        internal static string TimeSpanInXml {
            get {
                return ResourceManager.GetString("TimeSpanInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;odata.metadata&quot;:&quot;http://localhost/$metadata#Default.Container.WorkItems/@Element&quot;,&quot;odata.id&quot;:&quot;http://localhost/WorkItems(25)&quot;,&quot;odata.editLink&quot;:&quot;http://localhost/WorkItems(25)&quot;,&quot;odata.readLink&quot;:&quot;http://localhost/WorkItems(25)&quot;,&quot;ID&quot;:25,&quot;EmployeeID&quot;:0,&quot;IsCompleted&quot;:false,&quot;NumberOfHours@odata.type&quot;:&quot;Edm.Single&quot;,&quot;NumberOfHours&quot;:100
        ///}.
        /// </summary>
        internal static string WorkItemEntryInJsonLight {
            get {
                return ResourceManager.GetString("WorkItemEntryInJsonLight", resourceCulture);
            }
        }
    }
}
