//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Http.OData
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaselineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaselineResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Http.OData.BaselineResource", typeof(BaselineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;http://www.tempuri.org:8000/AbsoluteUri&lt;/d:ID&gt;.
        /// </summary>
        internal static string AbsoluteUri {
            get {
                return ResourceManager.GetString("AbsoluteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Boolean&quot;&gt;true&lt;/d:ID&gt;.
        /// </summary>
        internal static string Bool {
            get {
                return ResourceManager.GetString("Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Byte&quot;&gt;64&lt;/d:ID&gt;.
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Binary&quot;&gt;AAIgQID/&lt;/d:ID&gt;.
        /// </summary>
        internal static string ByteArray {
            get {
                return ResourceManager.GetString("ByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.DateTime&quot;&gt;2010-01-01T00:00:00&lt;/d:ID&gt;.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Decimal&quot;&gt;12345.99999&lt;/d:ID&gt;.
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Double&quot;&gt;99999.12345&lt;/d:ID&gt;.
        /// </summary>
        internal static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://localhost:8081/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///  &lt;id&gt;http://localhost:8081/People(10)&lt;/id&gt;
        ///  &lt;category term=&quot;System.Web.Http.OData.Formatter.FormatterPerson&quot; scheme=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/scheme&quot; /&gt;
        ///  &lt;link rel=&quot;edit&quot; href=&quot;http://localhost:8081/People(10)&quot; /&gt;
        ///  &lt;link [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntryTypePersonAtom {
            get {
                return ResourceManager.GetString("EntryTypePersonAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///  &quot;d&quot;:%
        ///    &quot;__metadata&quot;:%
        ///      &quot;id&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;uri&quot;:&quot;http://localhost:8081/People(10)&quot;,&quot;type&quot;:&quot;System.Web.Http.OData.Formatter.FormatterPerson&quot;
        ///    },&quot;PerId&quot;:10,&quot;Age&quot;:10,&quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,&quot;Name&quot;:&quot;Asha&quot;,&quot;Order&quot;:%
        ///      &quot;__metadata&quot;:%
        ///        &quot;type&quot;:&quot;System.Web.Http.OData.Formatter.FormatterOrder&quot;
        ///      },&quot;OrderAmount&quot;:235342,&quot;OrderName&quot;:&quot;FirstOrder&quot;
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string EntryTypePersonODataJson {
            get {
                return ResourceManager.GetString("EntryTypePersonODataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %&quot;Age&quot;:10,&quot;MyGuid&quot;:&quot;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&quot;,&quot;Name&quot;:&quot;Asha&quot;,&quot;Order&quot;:%&quot;OrderAmount&quot;:235342,&quot;OrderName&quot;:&quot;FirstOrder&quot;},&quot;PerId&quot;:10}.
        /// </summary>
        internal static string EntryTypePersonRegularJson {
            get {
                return ResourceManager.GetString("EntryTypePersonRegularJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Guid&quot;&gt;f99080c0-2f9e-472e-8c72-1a8ecd9f902d&lt;/d:ID&gt;.
        /// </summary>
        internal static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; m:type=&quot;Edm.Int16&quot;&gt;-32768&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int16 {
            get {
                return ResourceManager.GetString("Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.Int32&quot;&gt;-2147483648&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int32 {
            get {
                return ResourceManager.GetString("Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.Int64&quot;&gt;-9223372036854775808&lt;/d:ID&gt;.
        /// </summary>
        internal static string Int64 {
            get {
                return ResourceManager.GetString("Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.Boolean&quot;&gt;false&lt;/d:ID&gt;.
        /// </summary>
        internal static string NullableBool {
            get {
                return ResourceManager.GetString("NullableBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:null=&quot;true&quot; /&gt;.
        /// </summary>
        internal static string NullableInt {
            get {
                return ResourceManager.GetString("NullableInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Bread&lt;/title&gt;
        ///  &lt;summary type=&quot;text&quot;&gt;Whole grain bread&lt;/summary&gt;
        ///  &lt;updated&gt;2012-04-19T00:54:33Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;
        ///  &lt;category term=&quot;ODataDemo.Product&quot; scheme=&quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductInsertData {
            get {
                return ResourceManager.GetString("ProductInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:DataServiceVersion=&quot;2.0&quot;&gt;
        ///    &lt;Schema Namespace=&quot;ODataDemo&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2007/05/edm&quot;&gt;
        ///      &lt;EntityType Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductsCSDL {
            get {
                return ResourceManager.GetString("ProductsCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:anyURI xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;RelativeUri&lt;/d:anyURI&gt;.
        /// </summary>
        internal static string RelativeUri {
            get {
                return ResourceManager.GetString("RelativeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.SByte&quot;&gt;-128&lt;/d:ID&gt;.
        /// </summary>
        internal static string SByte {
            get {
                return ResourceManager.GetString("SByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.Single&quot;&gt;INF&lt;/d:ID&gt;.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;This is a Test String&lt;/d:ID&gt;.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:etag=&quot;W/&amp;quot;0&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;id&gt;http://services.odata.org/OData/OData.svc/Suppliers(0)&lt;/id&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Exotic Liquids&lt;/title&gt;
        ///  &lt;updated&gt;2012-04-19T04:30:47Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuppliersInsertData {
            get {
                return ResourceManager.GetString("SuppliersInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://services.odata.org/OData/OData.svc/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:etag=&quot;W/&amp;quot;0&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;id&gt;http://services.odata.org/OData/OData.svc/Suppliers(0)&lt;/id&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Exotic Liquids&lt;/title&gt;
        ///  &lt;updated&gt;2012-04-19T04:30:47Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name /&gt;
        ///  &lt;/author&gt;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuppliersPatchData {
            get {
                return ResourceManager.GetString("SuppliersPatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfboolean xmlns=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot;&gt;
        ///  &lt;element m:type=&quot;Edm.Boolean&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;true&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Boolean&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;false&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Boolean&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;true&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Boole [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestArrayOfBools {
            get {
                return ResourceManager.GetString("TestArrayOfBools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfint xmlns=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot;&gt;
        ///  &lt;element m:type=&quot;Edm.Int32&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;10&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Int32&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;20&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Int32&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;30&lt;/element&gt;
        ///  &lt;element m:type=&quot;Edm.Int32&quot; xmlns:m=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestArrayOfInts {
            get {
                return ResourceManager.GetString("TestArrayOfInts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfPerson xmlns=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot;&gt;
        ///  &lt;element m:type=&quot;http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///    &lt;Age m:type=&quot;Edm.Int32&quot;&gt;20&lt;/Age&gt;
        ///    &lt;FavoriteHobby m:type=&quot;HobbyActivity&quot;&gt;
        ///      &lt;ActivityName&gt;Xbox Gaming&lt;/ActivityName&gt;
        ///    &lt;/FavoriteHobby&gt;
        ///    &lt;FirstName&gt;Frank&lt;/FirstName&gt;
        ///    &lt;Gender&gt;Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCollectionOfPerson {
            get {
                return ResourceManager.GetString("TestCollectionOfPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:Person xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person&quot;&gt;
        ///  &lt;d:Age m:type=&quot;Edm.Int32&quot;&gt;20&lt;/d:Age&gt;
        ///  &lt;d:FavoriteHobby m:type=&quot;HobbyActivity&quot;&gt;
        ///    &lt;d:ActivityName&gt;Xbox Gaming&lt;/d:ActivityName&gt;
        ///  &lt;/d:FavoriteHobby&gt;
        ///  &lt;d:FirstName&gt;Frank&lt;/d:FirstName&gt;
        ///  &lt;d:Gender&gt;Male&lt;/d:Gend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestComplexTypePerson {
            get {
                return ResourceManager.GetString("TestComplexTypePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfintstring xmlns=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot;&gt;
        ///  &lt;element m:type=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///    &lt;Key m:type=&quot;Edm.Int32&quot;&gt;1&lt;/Key&gt;
        ///    &lt;Value&gt;Frank&lt;/Value&gt;
        ///  &lt;/element&gt;
        ///  &lt;element m:type=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring&quot; xmlns:m=&quot;http://schemas.microsof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDictionary {
            get {
                return ResourceManager.GetString("TestDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://www.tempuri.org/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;
        ///  &lt;link rel=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem&quot; type=&quot;application/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEntityTypeBasic {
            get {
                return ResourceManager.GetString("TestEntityTypeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://www.tempuri.org/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;
        ///  &lt;link rel=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem&quot; type=&quot;application/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEntityTypeWithMultipleKeys {
            get {
                return ResourceManager.GetString("TestEntityTypeWithMultipleKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://localhost/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;
        ///  &lt;id&gt;http://localhost/WorkItems(25)&lt;/id&gt;
        ///  &lt;category term=&quot;System.Web.Http.OData.TestCommon.Models.WorkItem&quot; scheme=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/schem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEntityWorkItem {
            get {
                return ResourceManager.GetString("TestEntityWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;entry xml:base=&quot;http://www.tempuri.org/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;
        ///  &lt;id&gt;http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/DerivedWorkItem(EmployeeID=0,WorkItemID=25)&lt;/id&gt;
        ///  &lt;category term=&quot;http://s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEntityWorkItemWithExplictKeys {
            get {
                return ResourceManager.GetString("TestEntityWorkItemWithExplictKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;feed xml:base=&quot;http://www.tempuri.org/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot;&gt;
        ///  &lt;entry&gt;
        ///    &lt;link rel=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestFeedOfEmployee {
            get {
                return ResourceManager.GetString("TestFeedOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfstring xmlns=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot;&gt;
        ///  &lt;element&gt;Frank&lt;/element&gt;
        ///  &lt;element&gt;Steve&lt;/element&gt;
        ///  &lt;element&gt;Tom&lt;/element&gt;
        ///  &lt;element&gt;Chandler&lt;/element&gt;
        ///&lt;/ArrayOfstring&gt;.
        /// </summary>
        internal static string TestListOfStrings {
            get {
                return ResourceManager.GetString("TestListOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;d:ID xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:type=&quot;Edm.Time&quot;&gt;PT1H&lt;/d:ID&gt;.
        /// </summary>
        internal static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
    }
}
