//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.WebPages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.WebPages.Resources.WebPageResources", typeof(WebPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required anti-forgery token was not supplied or was invalid..
        /// </summary>
        internal static string AntiForgeryToken_ValidationFailed {
            get {
                return ResourceManager.GetString("AntiForgeryToken_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly &quot;{0}&quot; is already registered..
        /// </summary>
        internal static string ApplicationPart_ModuleAlreadyRegistered {
            get {
                return ResourceManager.GetString("ApplicationPart_ModuleAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application module is already registered for virtual path &quot;{0}&quot;..
        /// </summary>
        internal static string ApplicationPart_ModuleAlreadyRegisteredForVirtualPath {
            get {
                return ResourceManager.GetString("ApplicationPart_ModuleAlreadyRegisteredForVirtualPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an application module with the name &quot;{0}&quot;..
        /// </summary>
        internal static string ApplicationPart_ModuleCannotBeFound {
            get {
                return ResourceManager.GetString("ApplicationPart_ModuleCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly &quot;{0}&quot; is not a registered application module..
        /// </summary>
        internal static string ApplicationPart_ModuleNotRegistered {
            get {
                return ResourceManager.GetString("ApplicationPart_ModuleNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource file &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ApplicationPart_ResourceNotFound {
            get {
                return ResourceManager.GetString("ApplicationPart_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index length must be exactly one..
        /// </summary>
        internal static string DynamicDictionary_InvalidNumberOfIndexes {
            get {
                return ResourceManager.GetString("DynamicDictionary_InvalidNumberOfIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be of type string or int when getting a value..
        /// </summary>
        internal static string DynamicHttpApplicationState_UseOnlyStringOrIntToGet {
            get {
                return ResourceManager.GetString("DynamicHttpApplicationState_UseOnlyStringOrIntToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be of type string when setting a value..
        /// </summary>
        internal static string DynamicHttpApplicationState_UseOnlyStringToSet {
            get {
                return ResourceManager.GetString("DynamicHttpApplicationState_UseOnlyStringToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter conversion from type &quot;{0}&quot; to type &quot;{1}&quot; failed. See the inner exception for more information..
        /// </summary>
        internal static string HtmlHelper_ConversionThrew {
            get {
                return ResourceManager.GetString("HtmlHelper_ConversionThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter conversion from type &quot;{0}&quot; to type &quot;{1}&quot; failed because no type converter can convert between these types..
        /// </summary>
        internal static string HtmlHelper_NoConverterExists {
            get {
                return ResourceManager.GetString("HtmlHelper_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An HttpContext is required to perform this operation. Check that this operation is being performed during a web request..
        /// </summary>
        internal static string HttpContextUnavailable {
            get {
                return ResourceManager.GetString("HttpContextUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; specified in &quot;{1}&quot; is an invalid value for the SessionState directive. Possible values are: &quot;{2}&quot;..
        /// </summary>
        internal static string SessionState_InvalidValue {
            get {
                return ResourceManager.GetString("SessionState_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most one SessionState value can be declared per page..
        /// </summary>
        internal static string SessionState_TooManyValues {
            get {
                return ResourceManager.GetString("SessionState_TooManyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestScope cannot be created when _AppStart is executing..
        /// </summary>
        internal static string StateStorage_RequestScopeNotAvailable {
            get {
                return ResourceManager.GetString("StateStorage_RequestScopeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage scope is read only..
        /// </summary>
        internal static string StateStorage_ScopeIsReadOnly {
            get {
                return ResourceManager.GetString("StateStorage_ScopeIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage scopes cannot be created when _AppStart is executing..
        /// </summary>
        internal static string StateStorage_StorageScopesCannotBeCreated {
            get {
                return ResourceManager.GetString("StateStorage_StorageScopesCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation parameter names in unobtrusive client validation rules cannot be empty. Client rule type: {0}.
        /// </summary>
        internal static string UnobtrusiveJavascript_ValidationParameterCannotBeEmpty {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationParameterCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation parameter names in unobtrusive client validation rules must start with a lowercase letter and consist of only lowercase letters or digits. Validation parameter name: {0}, client rule type: {1}.
        /// </summary>
        internal static string UnobtrusiveJavascript_ValidationParameterMustBeLegal {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationParameterMustBeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules cannot be empty. Client rule type: {0}.
        /// </summary>
        internal static string UnobtrusiveJavascript_ValidationTypeCannotBeEmpty {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules must consist of only lowercase letters. Invalid name: &quot;{0}&quot;, client rule type: {1}.
        /// </summary>
        internal static string UnobtrusiveJavascript_ValidationTypeMustBeLegal {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeMustBeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules must be unique. The following validation type was seen more than once: {0}.
        /// </summary>
        internal static string UnobtrusiveJavascript_ValidationTypeMustBeUnique {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UrlData collection is read-only..
        /// </summary>
        internal static string UrlData_ReadOnly {
            get {
                return ResourceManager.GetString("UrlData_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format is invalid..
        /// </summary>
        internal static string ValidationDefault_DataType {
            get {
                return ResourceManager.GetString("ValidationDefault_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values do not match..
        /// </summary>
        internal static string ValidationDefault_EqualsTo {
            get {
                return ResourceManager.GetString("ValidationDefault_EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a decimal between {0} and {1}..
        /// </summary>
        internal static string ValidationDefault_FloatRange {
            get {
                return ResourceManager.GetString("ValidationDefault_FloatRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an integer between {0} and {1}..
        /// </summary>
        internal static string ValidationDefault_IntegerRange {
            get {
                return ResourceManager.GetString("ValidationDefault_IntegerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is invalid..
        /// </summary>
        internal static string ValidationDefault_Regex {
            get {
                return ResourceManager.GetString("ValidationDefault_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string ValidationDefault_Required {
            get {
                return ResourceManager.GetString("ValidationDefault_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length: {0}..
        /// </summary>
        internal static string ValidationDefault_StringLength {
            get {
                return ResourceManager.GetString("ValidationDefault_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be between {0} and {1} characters..
        /// </summary>
        internal static string ValidationDefault_StringLengthRange {
            get {
                return ResourceManager.GetString("ValidationDefault_StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; cannot be requested directly because it calls the &quot;{1}&quot; method..
        /// </summary>
        internal static string WebPage_CannotRequestDirectly {
            get {
                return ResourceManager.GetString("WebPage_CannotRequestDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file could not be rendered because its extension &quot;{0}&quot; might not be supported: &quot;{1}&quot;..
        /// </summary>
        internal static string WebPage_FileNotSupported {
            get {
                return ResourceManager.GetString("WebPage_FileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; could not be rendered, because it does not exist or is not a valid page..
        /// </summary>
        internal static string WebPage_InvalidPageType {
            get {
                return ResourceManager.GetString("WebPage_InvalidPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout page &quot;{0}&quot; could not be found at the following path: &quot;{1}&quot;..
        /// </summary>
        internal static string WebPage_LayoutPageNotFound {
            get {
                return ResourceManager.GetString("WebPage_LayoutPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;RenderBody&quot; method has already been called..
        /// </summary>
        internal static string WebPage_RenderBodyAlreadyCalled {
            get {
                return ResourceManager.GetString("WebPage_RenderBodyAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;RenderBody&quot; method has not been called for layout page &quot;{0}&quot;..
        /// </summary>
        internal static string WebPage_RenderBodyNotCalled {
            get {
                return ResourceManager.GetString("WebPage_RenderBodyNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section already defined: &quot;{0}&quot;..
        /// </summary>
        internal static string WebPage_SectionAleadyDefined {
            get {
                return ResourceManager.GetString("WebPage_SectionAleadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;RenderSection&quot; method has already been called for the section named &quot;{0}&quot;..
        /// </summary>
        internal static string WebPage_SectionAleadyRendered {
            get {
                return ResourceManager.GetString("WebPage_SectionAleadyRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not defined: &quot;{0}&quot;..
        /// </summary>
        internal static string WebPage_SectionNotDefined {
            get {
                return ResourceManager.GetString("WebPage_SectionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following sections have been defined but have not been rendered for the layout page &quot;{0}&quot;: &quot;{1}&quot;..
        /// </summary>
        internal static string WebPage_SectionsNotRendered {
            get {
                return ResourceManager.GetString("WebPage_SectionsNotRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with leading underscores (&quot;_&quot;) cannot be served..
        /// </summary>
        internal static string WebPageRoute_UnderscoreBlocked {
            get {
                return ResourceManager.GetString("WebPageRoute_UnderscoreBlocked", resourceCulture);
            }
        }
    }
}
