trigger:
  branches:
    include:
    - master

pr:
  - master

name: $(date:yyyyMMdd)$(rev:.r)
variables:
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- name: NugetSecurityAnalysisWarningLevel
  value: none
- name: ProductBinPath
  value: $(Build.SourcesDirectory)\bin\$(BuildConfiguration)
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      jobs:
      - job: Main
        displayName: Main Build
        timeoutInMinutes: 240
        steps:
        - checkout: self
          fetchTags: false
        - template: pipelines/task-group-policheck-v1.yml@self
        - task: NuGetToolInstaller@0
          displayName: Use NuGet >=5.8.0
          inputs:
            versionSpec: '>=5.8.0'
        - task: PowerShell@2
          displayName: 'Setup .NET Framework Build Environment'
          inputs:
            targetType: 'inline'
            script: |
              # Force install .NET Framework 4.5.2 Developer Pack via direct download
              # This ensures the reference assemblies are properly registered with MSBuild
              
              Write-Host "Downloading .NET Framework 4.5.2 Developer Pack..."
              $url = "https://download.microsoft.com/download/4/3/B/43B61315-B2CE-4F5B-9E32-34CCA07B2F0E/NDP452-KB2901951-x86-x64-DevPack.exe"
              $output = "$env:TEMP\NDP452-KB2901951-x86-x64-DevPack.exe"
              
              # Download with timeout
              $webClient = New-Object System.Net.WebClient
              $webClient.DownloadTimeout = 300000  # 5 minutes timeout
              try {
                $webClient.DownloadFile($url, $output)
                Write-Host "Download completed successfully."
              } catch {
                Write-Host "Download failed: $($_.Exception.Message)"
                exit 1
              }
              
              if (Test-Path $output) {
                Write-Host "Installing .NET Framework 4.5.2 Developer Pack..."
                $process = Start-Process -FilePath $output -ArgumentList "/quiet", "/norestart" -Wait -PassThru
                Write-Host "Installation process completed with exit code: $($process.ExitCode)"
                
                # Verify installation by checking for reference assemblies
                $refAssembliesPath = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2"
                if (Test-Path $refAssembliesPath) {
                  Write-Host "Reference assemblies found at: $refAssembliesPath"
                } else {
                  Write-Host "Warning: Reference assemblies not found at expected location"
                }
                
                # Also check v4.5 path
                $refAssembliesPath45 = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5"
                if (Test-Path $refAssembliesPath45) {
                  Write-Host "Reference assemblies for v4.5 found at: $refAssembliesPath45"
                } else {
                  Write-Host "Warning: Reference assemblies for v4.5 not found"
                }
              } else {
                Write-Host "Download failed - installer not found"
                exit 1
              }
        - task: UseDotNet@2
          displayName: Use .NET Core sdk 2.x
          inputs:
            version: 2.x
        - task: UseDotNet@2
          displayName: Use .NET Core sdk 3.1
          inputs:
            version: 3.x
        - task: PowerShell@2
          displayName: 'Verify MSBuild .NET Framework Support'
          inputs:
            targetType: 'inline'
            script: |
              # Set MSBuild environment variables to ensure proper .NET Framework support
              Write-Host "Setting up MSBuild environment for .NET Framework builds..."
              
              # Check available .NET Framework versions
              $frameworkPath = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework"
              if (Test-Path $frameworkPath) {
                Write-Host "Available .NET Framework versions:"
                Get-ChildItem $frameworkPath | ForEach-Object { Write-Host "  - $($_.Name)" }
              }
              
              # Force MSBuild to use the correct reference assemblies path
              [Environment]::SetEnvironmentVariable("TargetFrameworkRootPath", "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework", "Process")
              Write-Host "Set TargetFrameworkRootPath to: ${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework"
              
              # Verify MSBuild can find .NET Framework 4.5
              $msbuildPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
              if (Test-Path $msbuildPath) {
                Write-Host "MSBuild found at: $msbuildPath"
                & $msbuildPath -version
              } else {
                Write-Host "Warning: MSBuild not found at expected location"
              }
        - task: NuGetCommand@2
          displayName: NuGet restore **\*.sln
          inputs:
            solution: sln/WebApiOData.AspNet.sln;sln/WebApiOData.AspNetCore.sln;sln/WebApiOData.E2E.AspNet.sln;sln/WebApiOData.E2E.AspNetCore.sln
        - task: VSBuild@1
          displayName: Build solution sln\WebApiOData.AspNet.sln
          inputs:
            solution: 'sln\WebApiOData.AspNet.sln '
            platform: $(BuildPlatform)
            configuration: $(BuildConfiguration)
        - task: VSBuild@1
          displayName: Build solution sln\WebApiOData.E2E.AspNet.sln
          inputs:
            solution: sln\WebApiOData.E2E.AspNet.sln
            platform: $(BuildPlatform)
            configuration: $(BuildConfiguration)
        - task: DotNetCoreCLI@2
          displayName: 'build Microsoft.AspNetCore.OData.csproj '
          inputs:
            projects: $(Build.SourcesDirectory)\src\Microsoft.AspNetCore.OData\Microsoft.AspNetCore.OData.csproj
            arguments: --configuration $(BuildConfiguration) --no-incremental
        - task: DotNetCoreCLI@2
          displayName: build .NET Core Unit test project
          inputs:
            projects: $(Build.SourcesDirectory)\test\UnitTest\Microsoft.AspNetCore.OData.Test\Microsoft.AspNetCore.OData.Test.csproj
            arguments: --configuration $(BuildConfiguration) --no-incremental
        - task: DotNetCoreCLI@2
          displayName: build .NET Core E2E test project
          inputs:
            projects: $(Build.SourcesDirectory)\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore\Microsoft.Test.E2E.AspNetCore.OData.csproj
            arguments: --configuration $(BuildConfiguration) --no-incremental
        - task: DotNetCoreCLI@2
          displayName: build .NET Core 3x E2E test project
          inputs:
            projects: $(Build.SourcesDirectory)\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj
            arguments: --configuration $(BuildConfiguration) --no-incremental
        - task: PowerShell@2
          displayName: PowerShell Script
          inputs:
            filePath: '$(Build.SourcesDirectory)\tools\MeasureCodeSharing.ps1 '
            arguments: $(Build.SourcesDirectory)
        - task: PowerShell@2
          displayName: Skip StrongName for Classic
          inputs:
            targetType: inline
            script: |
              $PROGRAMFILESX86 = [Environment]::GetFolderPath("ProgramFilesX86")
              $SN = $PROGRAMFILESX86 + "\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\sn.exe"
              $SNx64 = $PROGRAMFILESX86 + "\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe"
              & $SN /Vr $(Build.SourcesDirectory)\bin\Release\Microsoft.AspNet.OData.dll
              & $SNx64 /Vr $(Build.SourcesDirectory)\bin\Release\Microsoft.AspNet.OData.dll
              & $SN /Vr $(Build.SourcesDirectory)\bin\release\netstandard2.0\Microsoft.AspNetCore.OData.dll
              & $SNx64 /Vr $(Build.SourcesDirectory)\bin\release\netstandard2.0\Microsoft.AspNetCore.OData.dll
              & $SN /Vr $(Build.SourcesDirectory)\bin\Release\UnitTest\AspNet\Microsoft.AspNet.OData.Test.dll
              & $SNx64 /Vr $(Build.SourcesDirectory)\bin\Release\UnitTest\AspNet\Microsoft.AspNet.OData.Test.dll
              & $SN /Vr $(Build.SourcesDirectory)\bin\Release\E2ETest\AspNet\Microsoft.Test.E2E.AspNet.OData.dll
              & $SNx64 /Vr $(Build.SourcesDirectory)\bin\Release\E2ETest\AspNet\Microsoft.Test.E2E.AspNet.OData.dll
              & $SN /Vr $(Build.SourcesDirectory)\bin\release\E2ETest\AspNetCore\Microsoft.Test.E2E.AspNetCore.OData.dll
              & $SNx64 /Vr $(Build.SourcesDirectory)\bin\release\E2ETest\AspNetCore\Microsoft.Test.E2E.AspNetCore.OData.dll
        - task: VSTest@2
          displayName: Classic Unit Tests (Microsoft.AspNet.OData.Test.dll)
          inputs:
            testAssemblyVer2: '**\bin\**\UnitTest\**\Microsoft.AspNet.OData.Test.dll'
        - task: DotNetCoreCLI@2
          displayName: 'Core Unit Tests (Microsoft.AspNetCore.OData.Test.csproj) '
          inputs:
            command: test
            projects: $(Build.SourcesDirectory)\test\UnitTest\Microsoft.AspNetCore.OData.Test\Microsoft.AspNetCore.OData.Test.csproj
            arguments: --configuration $(BuildConfiguration) --no-build
        - task: VSTest@2
          displayName: Classic E2E Tests (Microsoft.Test.E2E.AspNet.OData.dll)
          inputs:
            testAssemblyVer2: '**\bin\**\E2ETest\**\Microsoft.Test.E2E.AspNet.OData.dll'
            testFiltercriteria: (DisplayName!=Microsoft.Test.E2E.AspNet.OData.ODataPathHandler.UnicodeRouteTests_Todoü.CRUDEntitySetShouldWork)
        - task: DotNetCoreCLI@2
          displayName: Core E2E Tests (Microsoft.Test.E2E.AspNetCore.OData.csproj)
          inputs:
            command: test
            projects: $(Build.SourcesDirectory)\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore\Microsoft.Test.E2E.AspNetCore.OData.csproj
            arguments: --configuration $(BuildConfiguration) --no-build
        - task: DotNetCoreCLI@2
          displayName: Core E2E 3x Tests (Microsoft.Test.E2E.AspNetCore3x.OData.csproj)
          inputs:
            command: test
            projects: $(Build.SourcesDirectory)\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj
            arguments: --configuration $(BuildConfiguration) --no-build --filter FullyQualifiedName!=Microsoft.Test.E2E.AspNet.OData.QueryComposition.SelectExpandEFTests.QueryForLongSelectList -v diag