trigger:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: self
    type: git
    ref: master

pr:
  - master
variables:
  BuildPlatform: 'Any Cpu'
  BuildConfiguration: 'Release'
stages: 
- stage: Build
  jobs:
    - job: Main
      displayName: Main Build
      # setting a 3hour timeout as webapi tests normally take about 2hr 30 mins
      timeoutInMinutes: 180

      pool:
        vmImage: windows-latest

      steps:
        - template: ./common.yml
