//-----------------------------------------------------------------------------
// <copyright file="DefaultBatchGeneratedClient.cs" company=".NET Foundation">
//      Copyright (c) .NET Foundation and Contributors. All rights reserved. 
//      See License.txt in the project root for license information.
// </copyright>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 4/9/2014 5:52:38 AM
namespace Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public Container(global::System.Uri serviceRoot) :
            base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient", "Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DefaultBatchCustomer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<DefaultBatchCustomer> DefaultBatchCustomer
        {
            get
            {
                if ((this._DefaultBatchCustomer == null))
                {
                    this._DefaultBatchCustomer = base.CreateQuery<DefaultBatchCustomer>("DefaultBatchCustomer");
                }
                return this._DefaultBatchCustomer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<DefaultBatchCustomer> _DefaultBatchCustomer;
        /// <summary>
        /// There are no comments for DefaultBatchOrder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<DefaultBatchOrder> DefaultBatchOrder
        {
            get
            {
                if ((this._DefaultBatchOrder == null))
                {
                    this._DefaultBatchOrder = base.CreateQuery<DefaultBatchOrder>("DefaultBatchOrder");
                }
                return this._DefaultBatchOrder;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<DefaultBatchOrder> _DefaultBatchOrder;
        /// <summary>
        /// There are no comments for DefaultBatchCustomer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToDefaultBatchCustomer(DefaultBatchCustomer defaultBatchCustomer)
        {
            base.AddObject("DefaultBatchCustomer", defaultBatchCustomer);
        }
        /// <summary>
        /// There are no comments for DefaultBatchOrder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToDefaultBatchOrder(DefaultBatchOrder defaultBatchOrder)
        {
            base.AddObject("DefaultBatchOrder", defaultBatchOrder);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DefaultBatchCustomer"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""Orders"" Type=""Collection(Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.DefaultBatchOrder)"" />
      </EntityType>
      <EntityType Name=""DefaultBatchOrder"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PurchaseDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
      </EntityType>
      <Action Name=""OddCustomers"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.DefaultBatchCustomer)"" />
        <ReturnType Type=""Collection(Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.DefaultBatchCustomer)"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""DefaultBatchCustomer"" EntityType=""Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.DefaultBatchCustomer"">
          <NavigationPropertyBinding Path=""Orders"" Target=""DefaultBatchOrder"" />
        </EntitySet>
        <EntitySet Name=""DefaultBatchOrder"" EntityType=""Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DataServicesClient.DefaultBatchOrder"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for DefaultBatchCustomer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class DefaultBatchCustomer
    {
        /// <summary>
        /// Create a new DefaultBatchCustomer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DefaultBatchCustomer CreateDefaultBatchCustomer(int ID)
        {
            DefaultBatchCustomer defaultBatchCustomer = new DefaultBatchCustomer();
            defaultBatchCustomer.Id = ID;
            return defaultBatchCustomer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy.DefaultBatchOrder> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                this.OnOrdersChanging(value);
                this._Orders = value;
                this.OnOrdersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy.DefaultBatchOrder> _Orders = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy.DefaultBatchOrder>();
        partial void OnOrdersChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Test.E2E.AspNet.OData.Batch.Tests.DefaultBatchProxy.DefaultBatchOrder> value);
        partial void OnOrdersChanged();
    }
    /// <summary>
    /// There are no comments for DefaultBatchOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class DefaultBatchOrder
    {
        /// <summary>
        /// Create a new DefaultBatchOrder object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="purchaseDate">Initial value of PurchaseDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DefaultBatchOrder CreateDefaultBatchOrder(int ID, global::System.DateTimeOffset purchaseDate)
        {
            DefaultBatchOrder defaultBatchOrder = new DefaultBatchOrder();
            defaultBatchOrder.Id = ID;
            defaultBatchOrder.PurchaseDate = purchaseDate;
            return defaultBatchOrder;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property PurchaseDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::System.DateTimeOffset PurchaseDate
        {
            get
            {
                return this._PurchaseDate;
            }
            set
            {
                this.OnPurchaseDateChanging(value);
                this._PurchaseDate = value;
                this.OnPurchaseDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::System.DateTimeOffset _PurchaseDate;
        partial void OnPurchaseDateChanging(global::System.DateTimeOffset value);
        partial void OnPurchaseDateChanged();
    }
}
