//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMatrix.WebData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebDataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMatrix.WebData.Resources.WebDataResources", typeof(WebDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database operation failed..
        /// </summary>
        internal static string Security_DbFailure {
            get {
                return ResourceManager.GetString("Security_DbFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user table found that has the name &quot;{0}&quot;..
        /// </summary>
        internal static string Security_FailedToFindUserTable {
            get {
                return ResourceManager.GetString("Security_FailedToFindUserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;WebSecurity.InitializeDatabaseConnection&quot; method can be called only once..
        /// </summary>
        internal static string Security_InitializeAlreadyCalled {
            get {
                return ResourceManager.GetString("Security_InitializeAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must call the &quot;WebSecurity.InitializeDatabaseConnection&quot; method before you call any other method of the &quot;WebSecurity&quot; class. This call should be placed in an _AppStart.cshtml file in the root of your site..
        /// </summary>
        internal static string Security_InitializeMustBeCalledFirst {
            get {
                return ResourceManager.GetString("Security_InitializeMustBeCalledFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account exists for &quot;{0}&quot;..
        /// </summary>
        internal static string Security_NoAccountFound {
            get {
                return ResourceManager.GetString("Security_NoAccountFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To call this method, the &quot;Membership.Provider&quot; property must be an instance of &quot;ExtendedMembershipProvider&quot;..
        /// </summary>
        internal static string Security_NoExtendedMembershipProvider {
            get {
                return ResourceManager.GetString("Security_NoExtendedMembershipProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found was found that has the name &quot;{0}&quot;..
        /// </summary>
        internal static string Security_NoUserFound {
            get {
                return ResourceManager.GetString("Security_NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to store OAuth token to database..
        /// </summary>
        internal static string SimpleMembership_FailToStoreOAuthToken {
            get {
                return ResourceManager.GetString("SimpleMembership_FailToStoreOAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The membership password is too long. (Maximum length is 128 characters)..
        /// </summary>
        internal static string SimpleMembership_PasswordTooLong {
            get {
                return ResourceManager.GetString("SimpleMembership_PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider unrecognized attribute: &quot;{0}&quot;..
        /// </summary>
        internal static string SimpleMembership_ProviderUnrecognizedAttribute {
            get {
                return ResourceManager.GetString("SimpleMembership_ProviderUnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &quot;{0}&quot; cannot be deleted because there are still users in the role..
        /// </summary>
        internal static string SimpleRoleProvder_RolePopulated {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_RolePopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; is already in role &quot;{1}&quot;..
        /// </summary>
        internal static string SimpleRoleProvder_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; is not in role &quot;{1}&quot;..
        /// </summary>
        internal static string SimpleRoleProvder_UserNotInRole {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role found that has the name &quot;{0}&quot;..
        /// </summary>
        internal static string SimpleRoleProvider_NoRoleFound {
            get {
                return ResourceManager.GetString("SimpleRoleProvider_NoRoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &quot;{0}&quot; already exists..
        /// </summary>
        internal static string SimpleRoleProvider_RoleExists {
            get {
                return ResourceManager.GetString("SimpleRoleProvider_RoleExists", resourceCulture);
            }
        }
    }
}
