//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Http.OData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Http.OData.Properties.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpActionContext.ActionDescriptor is null..
        /// </summary>
        internal static string ActionContextMustHaveDescriptor {
            get {
                return ResourceManager.GetString("ActionContextMustHaveDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpActionContext.Request is null..
        /// </summary>
        internal static string ActionContextMustHaveRequest {
            get {
                return ResourceManager.GetString("ActionContextMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpActionExecutedContext.ActionContext is null..
        /// </summary>
        internal static string ActionExecutedContextMustHaveActionContext {
            get {
                return ResourceManager.GetString("ActionExecutedContextMustHaveActionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpExecutedActionContext.Request is null..
        /// </summary>
        internal static string ActionExecutedContextMustHaveRequest {
            get {
                return ResourceManager.GetString("ActionExecutedContextMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; is not bound to an entity. Only actions that are bound to entities can have action links..
        /// </summary>
        internal static string ActionNotBoundToEntity {
            get {
                return ResourceManager.GetString("ActionNotBoundToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action resolution failed. Multiple actions matching the action identifier &apos;{0}&apos; were found. The matching actions are: {1}..
        /// </summary>
        internal static string ActionResolutionFailed {
            get {
                return ResourceManager.GetString("ActionResolutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query option is not bound to any CLR type. &apos;{0}&apos; is only supported with a query option bound to a CLR type..
        /// </summary>
        internal static string ApplyToOnUntypedQueryOption {
            get {
                return ResourceManager.GetString("ApplyToOnUntypedQueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have &apos;{0}&apos; as the media type..
        /// </summary>
        internal static string BatchRequestInvalidMediaType {
            get {
                return ResourceManager.GetString("BatchRequestInvalidMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have a boundary specification in the &quot;Content-Type&quot; header..
        /// </summary>
        internal static string BatchRequestMissingBoundary {
            get {
                return ResourceManager.GetString("BatchRequestMissingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Content&apos; property on the batch request cannot be null..
        /// </summary>
        internal static string BatchRequestMissingContent {
            get {
                return ResourceManager.GetString("BatchRequestMissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch request must have a &quot;Content-Type&quot; header..
        /// </summary>
        internal static string BatchRequestMissingContentType {
            get {
                return ResourceManager.GetString("BatchRequestMissingContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A binary operator with incompatible types was detected. Found operand types &apos;{0}&apos; and &apos;{1}&apos; for operator kind &apos;{2}&apos;..
        /// </summary>
        internal static string BinaryOperatorNotSupported {
            get {
                return ResourceManager.GetString("BinaryOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on type &apos;{1}&apos; returned a null value. The input stream contains collection items which cannot be added if the instance is null..
        /// </summary>
        internal static string CannotAddToNullCollection {
            get {
                return ResourceManager.GetString("CannotAddToNullCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply {0} of &apos;{1}&apos; to {2} of &apos;{3}&apos;..
        /// </summary>
        internal static string CannotApplyODataQueryOptionsOfT {
            get {
                return ResourceManager.GetString("CannotApplyODataQueryOptionsOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot automatically bind the navigation property &apos;{0}&apos; on entity type &apos;{1}&apos; for the source entity set &apos;{2}&apos; because there are two or more matching target entity sets. The matching entity sets are: {3}..
        /// </summary>
        internal static string CannotAutoCreateMultipleCandidates {
            get {
                return ResourceManager.GetString("CannotAutoCreateMultipleCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast $filter of type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCastFilter {
            get {
                return ResourceManager.GetString("CannotCastFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define keys on type &apos;{0}&apos; deriving from &apos;{1}&apos;. Only the root type in the entity inheritance hierarchy can contain keys..
        /// </summary>
        internal static string CannotDefineKeysOnDerivedTypes {
            get {
                return ResourceManager.GetString("CannotDefineKeysOnDerivedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the abstract entity type &apos;{0}&apos; was found. Abstract entity types cannot be instantiated..
        /// </summary>
        internal static string CannotInstantiateAbstractEntityType {
            get {
                return ResourceManager.GetString("CannotInstantiateAbstractEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert &apos;{0}&apos; to an integer..
        /// </summary>
        internal static string CanNotParseInteger {
            get {
                return ResourceManager.GetString("CanNotParseInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply PATCH to navigation property &apos;{0}&apos; on entity type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotPatchNavigationProperties {
            get {
                return ResourceManager.GetString("CannotPatchNavigationProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot redefine property &apos;{0}&apos; already defined on the base type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotRedefineBaseTypeProperty {
            get {
                return ResourceManager.GetString("CannotRedefineBaseTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize a null &apos;{0}&apos;..
        /// </summary>
        internal static string CannotSerializerNull {
            get {
                return ResourceManager.GetString("CannotSerializerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot write an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotWriteType {
            get {
                return ResourceManager.GetString("CannotWriteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given model does not contain the type &apos;{0}&apos;..
        /// </summary>
        internal static string ClrTypeNotInModel {
            get {
                return ResourceManager.GetString("ClrTypeNotInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectionProperties must implement IEnumerable&lt;&gt;. The property &apos;{0}&apos; declared on &apos;{1}&apos; does not implement IEnumerable&lt;&gt;..
        /// </summary>
        internal static string CollectionPropertiesMustReturnIEnumerable {
            get {
                return ResourceManager.GetString("CollectionPropertiesMustReturnIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; does not have an Add method. Consider using a collection type that does have an Add method - for example IList&lt;T&gt; or ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionShouldHaveAddMethod {
            get {
                return ResourceManager.GetString("CollectionShouldHaveAddMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; does not have a Clear method. Consider using a collection type that does have a Clear method, such as IList&lt;T&gt; or ICollection&lt;T&gt;..
        /// </summary>
        internal static string CollectionShouldHaveClearMethod {
            get {
                return ResourceManager.GetString("CollectionShouldHaveClearMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complex type &apos;{0}&apos; refers to the entity type &apos;{1}&apos; through the property &apos;{2}&apos;..
        /// </summary>
        internal static string ComplexTypeRefersToEntityType {
            get {
                return ResourceManager.GetString("ComplexTypeRefersToEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare an enum of type &apos;{0}&apos; to an expression of type &apos;{1}&apos;..
        /// </summary>
        internal static string ConvertToEnumFailed {
            get {
                return ResourceManager.GetString("ConvertToEnumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support CreateODataValue..
        /// </summary>
        internal static string CreateODataValueNotSupported {
            get {
                return ResourceManager.GetString("CreateODataValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual entity type &apos;{0}&apos; is not assignable to the expected type &apos;{1}&apos;..
        /// </summary>
        internal static string DeltaEntityTypeNotAssignable {
            get {
                return ResourceManager.GetString("DeltaEntityTypeNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use Delta of type &apos;{0}&apos; on an entity of type &apos;{1}&apos;..
        /// </summary>
        internal static string DeltaTypeMismatch {
            get {
                return ResourceManager.GetString("DeltaTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not support Read..
        /// </summary>
        internal static string DeserializerDoesNotSupportRead {
            get {
                return ResourceManager.GetString("DeserializerDoesNotSupportRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not support ReadInline..
        /// </summary>
        internal static string DoesNotSupportReadInLine {
            get {
                return ResourceManager.GetString("DoesNotSupportReadInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edit link builder for the entity set &apos;{0}&apos; returned null. An edit link is required for the location header..
        /// </summary>
        internal static string EditLinkNullForLocationHeader {
            get {
                return ResourceManager.GetString("EditLinkNullForLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get property &apos;{0}&apos; of a null EDM object of type &apos;{1}&apos;..
        /// </summary>
        internal static string EdmComplexObjectNullRef {
            get {
                return ResourceManager.GetString("EdmComplexObjectNullRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;EdmObject&apos; of {0} cannot be null..
        /// </summary>
        internal static string EdmObjectNull {
            get {
                return ResourceManager.GetString("EdmObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type of the object of type &apos;{0}&apos; is null. The EDM type of an {1} cannot be null..
        /// </summary>
        internal static string EdmTypeCannotBeNull {
            get {
                return ResourceManager.GetString("EdmTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported EDM type..
        /// </summary>
        internal static string EdmTypeNotSupported {
            get {
                return ResourceManager.GetString("EdmTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;ElementClrType&apos; of {0} cannot be null..
        /// </summary>
        internal static string ElementClrTypeNull {
            get {
                return ResourceManager.GetString("ElementClrTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity set &apos;{0}&apos; was already configured with a different EntityType (&apos;{1}&apos;)..
        /// </summary>
        internal static string EntitySetAlreadyConfiguredDifferentEntityType {
            get {
                return ResourceManager.GetString("EntitySetAlreadyConfiguredDifferentEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string EntitySetControllerErrorMessageLanguage {
            get {
                return ResourceManager.GetString("EntitySetControllerErrorMessageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service doesn&apos;t support OData requests in the form &apos;{0}&apos;..
        /// </summary>
        internal static string EntitySetControllerUnmappedRequest {
            get {
                return ResourceManager.GetString("EntitySetControllerUnmappedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented..
        /// </summary>
        internal static string EntitySetControllerUnmappedRequestErrorCode {
            get {
                return ResourceManager.GetString("EntitySetControllerUnmappedRequestErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating entities is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedCreate {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a &apos;{0}&apos; link is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedCreateLink {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating link failed..
        /// </summary>
        internal static string EntitySetControllerUnsupportedCreateLinkErrorCode {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedCreateLinkErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting entities is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedDelete {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a &apos;{0}&apos; link is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedDeleteLink {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedDeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting link failed..
        /// </summary>
        internal static string EntitySetControllerUnsupportedDeleteLinkErrorCode {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedDeleteLinkErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting entities is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedGet {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting entities by key is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedGetByKey {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedGetByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET requests by key are not supported..
        /// </summary>
        internal static string EntitySetControllerUnsupportedGetByKeyErrorCode {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedGetByKeyErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting the key from entity instances is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedGetKey {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedGetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requests are not supported..
        /// </summary>
        internal static string EntitySetControllerUnsupportedMethodErrorCode {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedMethodErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching entities is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedPatch {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing entities is not supported for this entity set..
        /// </summary>
        internal static string EntitySetControllerUnsupportedUpdate {
            get {
                return ResourceManager.GetString("EntitySetControllerUnsupportedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related entity set could not be found from the OData path. The related entity set is required to deserialize the payload..
        /// </summary>
        internal static string EntitySetMissingDuringDeserialization {
            get {
                return ResourceManager.GetString("EntitySetMissingDuringDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related entity set could not be found from the OData path. The related entity set is required to serialize the payload..
        /// </summary>
        internal static string EntitySetMissingDuringSerialization {
            get {
                return ResourceManager.GetString("EntitySetMissingDuringSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EntitySet exists in the EdmModel with entitySetName &apos;{0}&apos;..
        /// </summary>
        internal static string EntitySetNotFoundForName {
            get {
                return ResourceManager.GetString("EntitySetNotFoundForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; does not match the expected entity type &apos;{1}&apos; as set on the query context..
        /// </summary>
        internal static string EntityTypeMismatch {
            get {
                return ResourceManager.GetString("EntityTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the entity type &apos;{0}&apos; in the model..
        /// </summary>
        internal static string EntityTypeNotInModel {
            get {
                return ResourceManager.GetString("EntityTypeNotInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported by the ODataErrorSerializer. The type must be ODataError or HttpError..
        /// </summary>
        internal static string ErrorTypeMustBeODataErrorOrHttpError {
            get {
                return ResourceManager.GetString("ErrorTypeMustBeODataErrorOrHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an EDM model as the action &apos;{0}&apos; on controller &apos;{1}&apos; has a void return type..
        /// </summary>
        internal static string FailedToBuildEdmModelBecauseReturnTypeIsNull {
            get {
                return ResourceManager.GetString("FailedToBuildEdmModelBecauseReturnTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an EDM model as the action &apos;{0}&apos; on controller &apos;{1}&apos; has a return type &apos;{2}&apos; that does not implement IEnumerable&lt;T&gt;..
        /// </summary>
        internal static string FailedToRetrieveTypeToBuildEdmModel {
            get {
                return ResourceManager.GetString("FailedToRetrieveTypeToBuildEdmModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading type &apos;{0}&apos; is not supported by &apos;{1}&apos;..
        /// </summary>
        internal static string FormatterReadIsNotSupportedForType {
            get {
                return ResourceManager.GetString("FormatterReadIsNotSupportedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a valid EDM primitive. The [FromODataUri] attribute can only be used on parameters with types that correspond to EDM primitives..
        /// </summary>
        internal static string FromODataUriRequiresPrimitive {
            get {
                return ResourceManager.GetString("FromODataUriRequiresPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; function cannot be applied to an enumeration-typed argument..
        /// </summary>
        internal static string FunctionNotSupportedOnEnum {
            get {
                return ResourceManager.GetString("FunctionNotSupportedOnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEdmModel cannot be called more than once. Consider using a different instance of the model builder or reusing the model you have built earlier..
        /// </summary>
        internal static string GetEdmModelCalledMoreThanOnce {
            get {
                return ResourceManager.GetString("GetEdmModelCalledMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property &apos;{0}&apos; on type &apos;{1}&apos; is an array. Consider adding a setter for the property..
        /// </summary>
        internal static string GetOnlyCollectionCannotBeArray {
            get {
                return ResourceManager.GetString("GetOnlyCollectionCannotBeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register an action link factory, actions must be bindable to a single entity. Action &apos;{0}&apos; does not meet this requirement..
        /// </summary>
        internal static string HasActionLinkRequiresBindToEntity {
            get {
                return ResourceManager.GetString("HasActionLinkRequiresBindToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current batch reader state &apos;{0}&apos; is invalid. The expected state is &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidBatchReaderState {
            get {
                return ResourceManager.GetString("InvalidBatchReaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bindingParameter type &apos;{0}&apos;. A bindingParameter must be either an EntityType or a Collection of EntityTypes..
        /// </summary>
        internal static string InvalidBindingParameterType {
            get {
                return ResourceManager.GetString("InvalidBindingParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast encountered. Cast type &apos;{0}&apos; must be the same as or derive from the previous segment&apos;s type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCastInPath {
            get {
                return ResourceManager.GetString("InvalidCastInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid entity set name..
        /// </summary>
        internal static string InvalidEntitySetName {
            get {
                return ResourceManager.GetString("InvalidEntitySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for $inlinecount..
        /// </summary>
        internal static string InvalidInlineCount {
            get {
                return ResourceManager.GetString("InvalidInlineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter type &apos;{0}&apos;. A non-binding parameter type must be either Primitive, Complex, Collection of Primitive or a Collection of Complex..
        /// </summary>
        internal static string InvalidParameterType {
            get {
                return ResourceManager.GetString("InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI segment &apos;{0}&apos; is invalid after the segment &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidPathSegment {
            get {
                return ResourceManager.GetString("InvalidPathSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapper provider must return a valid &apos;{0}&apos; instance for the given &apos;{1}&apos; IEdmType..
        /// </summary>
        internal static string InvalidPropertyMapper {
            get {
                return ResourceManager.GetString("InvalidPropertyMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key mapping for the property &apos;{0}&apos; can&apos;t be null or empty..
        /// </summary>
        internal static string InvalidPropertyMapping {
            get {
                return ResourceManager.GetString("InvalidPropertyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key property &apos;{0}&apos; of type &apos;{1}&apos; is null. Key properties cannot have null values..
        /// </summary>
        internal static string KeyValueCannotBeNull {
            get {
                return ResourceManager.GetString("KeyValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LambdaExpression must have exactly one parameter..
        /// </summary>
        internal static string LambdaExpressionMustHaveExactlyOneParameter {
            get {
                return ResourceManager.GetString("LambdaExpressionMustHaveExactlyOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Location header could not be generated because the request&apos;s OData path does not start with an entity set path segment..
        /// </summary>
        internal static string LocationHeaderDoesNotStartWithEntitySet {
            get {
                return ResourceManager.GetString("LocationHeaderDoesNotStartWithEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Location header could not be generated because the request does not have an associated OData path..
        /// </summary>
        internal static string LocationHeaderMissingODataPath {
            get {
                return ResourceManager.GetString("LocationHeaderMissingODataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change multiplicity of the collection navigation property &apos;{0}&apos;..
        /// </summary>
        internal static string ManyNavigationPropertiesCannotBeChanged {
            get {
                return ResourceManager.GetString("ManyNavigationPropertiesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on the type &apos;{1}&apos; is being configured as a Many-to-Many navigation property. Many to Many navigation properties must be collections..
        /// </summary>
        internal static string ManyToManyNavigationPropertyMustReturnCollection {
            get {
                return ResourceManager.GetString("ManyToManyNavigationPropertyMustReturnCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided mapping doesn&apos;t contain an entry for the entity type &apos;{0}&apos;..
        /// </summary>
        internal static string MappingDoesNotContainEntityType {
            get {
                return ResourceManager.GetString("MappingDoesNotContainEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Any/All nesting limit of &apos;{0}&apos; has been exceeded. &apos;{1}&apos; can be configured on ODataQuerySettings or EnableQueryAttribute..
        /// </summary>
        internal static string MaxAnyAllExpressionLimitExceeded {
            get {
                return ResourceManager.GetString("MaxAnyAllExpressionLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request includes a $expand path which is too deep. The maximum depth allowed is {0}. To increase the limit, set the &apos;{1}&apos; property on EnableQueryAttribute or ODataValidationSettings..
        /// </summary>
        internal static string MaxExpandDepthExceeded {
            get {
                return ResourceManager.GetString("MaxExpandDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node count limit of &apos;{0}&apos; has been exceeded. To increase the limit, set the &apos;{1}&apos; property on EnableQueryAttribute or ODataValidationSettings..
        /// </summary>
        internal static string MaxNodeLimitExceeded {
            get {
                return ResourceManager.GetString("MaxNodeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberExpressions must be bound to the LambdaExpression parameter..
        /// </summary>
        internal static string MemberExpressionsMustBeBoundToLambdaParameter {
            get {
                return ResourceManager.GetString("MemberExpressionsMustBeBoundToLambdaParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}.{1}&apos; is not a property..
        /// </summary>
        internal static string MemberExpressionsMustBeProperties {
            get {
                return ResourceManager.GetString("MemberExpressionsMustBeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding context cannot have a null ModelMetadata..
        /// </summary>
        internal static string ModelBinderUtil_ModelMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM model is missing on the read context. The model is required on the read context to deserialize the payload..
        /// </summary>
        internal static string ModelMissingFromReadContext {
            get {
                return ResourceManager.GetString("ModelMissingFromReadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Procedure called &apos;{0}&apos; was found. Try using the other RemoveProcedure override..
        /// </summary>
        internal static string MoreThanOneProcedureFound {
            get {
                return ResourceManager.GetString("MoreThanOneProcedureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; on type &apos;{1}&apos; contains multiple instances of the attribute &apos;{2}&apos;..
        /// </summary>
        internal static string MultipleAttributesFound {
            get {
                return ResourceManager.GetString("MultipleAttributesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one matching CLR type found for the EDM type {0}.\nThe matching CLR types are {1}..
        /// </summary>
        internal static string MultipleMatchingClrTypesForEdmType {
            get {
                return ResourceManager.GetString("MultipleMatchingClrTypesForEdmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property on &apos;{1}&apos; must be a Collection property..
        /// </summary>
        internal static string MustBeCollectionProperty {
            get {
                return ResourceManager.GetString("MustBeCollectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on type &apos;{1}&apos; must be a Complex property..
        /// </summary>
        internal static string MustBeComplexProperty {
            get {
                return ResourceManager.GetString("MustBeComplexProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property  &apos;{0}&apos; on type &apos;{1}&apos; must be a Navigation property..
        /// </summary>
        internal static string MustBeNavigationProperty {
            get {
                return ResourceManager.GetString("MustBeNavigationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos;  on type &apos;{1}&apos; must be a Primitive property..
        /// </summary>
        internal static string MustBePrimitiveProperty {
            get {
                return ResourceManager.GetString("MustBePrimitiveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be a primitive type..
        /// </summary>
        internal static string MustBePrimitiveType {
            get {
                return ResourceManager.GetString("MustBePrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The multiplicity of the &apos;{0}&apos; property must be &apos;{1}&apos;..
        /// </summary>
        internal static string MustHaveMatchingMultiplicity {
            get {
                return ResourceManager.GetString("MustHaveMatchingMultiplicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related navigation property could not be found from the OData path. The related navigation property is required to deserialize the payload..
        /// </summary>
        internal static string NavigationPropertyMissingDuringDeserialization {
            get {
                return ResourceManager.GetString("NavigationPropertyMissingDuringDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related navigation property could not be found from the OData path. The related navigation property is required to serialize the payload..
        /// </summary>
        internal static string NavigationPropertyMissingDuringSerialization {
            get {
                return ResourceManager.GetString("NavigationPropertyMissingDuringSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find navigation property &apos;{0}&apos; on the entity type &apos;{1}&apos;..
        /// </summary>
        internal static string NavigationPropertyNotfound {
            get {
                return ResourceManager.GetString("NavigationPropertyNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The declaring entity type &apos;{0}&apos; of the given navigation property is not a part of the entity type &apos;{1}&apos; hierarchy of the entity set &apos;{2}&apos;..
        /// </summary>
        internal static string NavigationPropertyNotInHierarchy {
            get {
                return ResourceManager.GetString("NavigationPropertyNotInHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action detected. &apos;{0}&apos; is not an action that can bind to &apos;Collection({1})&apos;..
        /// </summary>
        internal static string NoActionFoundForCollection {
            get {
                return ResourceManager.GetString("NoActionFoundForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IdLink factory was found. Try calling HasIdLink on the EntitySetConfiguration for &apos;{0}&apos;..
        /// </summary>
        internal static string NoIdLinkFactoryFound {
            get {
                return ResourceManager.GetString("NoIdLinkFactoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IEdmType could be found for &apos;{0}&apos;..
        /// </summary>
        internal static string NoMatchingIEdmTypeFound {
            get {
                return ResourceManager.GetString("NoMatchingIEdmTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTTP resource was found that matches the request URI &apos;{0}&apos;..
        /// </summary>
        internal static string NoMatchingResource {
            get {
                return ResourceManager.GetString("NoMatchingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NavigationLink factory was found for the navigation property &apos;{0}&apos; from entity type &apos;{1}&apos; on entity set &apos;{2}&apos;. Try calling HasNavigationPropertyLink on the EntitySetConfiguration..
        /// </summary>
        internal static string NoNavigationLinkFactoryFound {
            get {
                return ResourceManager.GetString("NoNavigationLinkFactoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is not a collection. Query options $filter, $orderby, $inlinecount, $skip, and $top can be applied only on collections..
        /// </summary>
        internal static string NonSelectExpandOnSingleEntity {
            get {
                return ResourceManager.GetString("NonSelectExpandOnSingleEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routing convention was found to select an action for the OData path with template &apos;{0}&apos;..
        /// </summary>
        internal static string NoRoutingHandlerToSelectAction {
            get {
                return ResourceManager.GetString("NoRoutingHandlerToSelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic operator &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedArithmeticOperator {
            get {
                return ResourceManager.GetString("NotAllowedArithmeticOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedFunction {
            get {
                return ResourceManager.GetString("NotAllowedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical operator &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedLogicalOperator {
            get {
                return ResourceManager.GetString("NotAllowedLogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedOrderByProperty {
            get {
                return ResourceManager.GetString("NotAllowedOrderByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query option &apos;{0}&apos; is not allowed. To allow it, set the &apos;{1}&apos; property on EnableQueryAttribute or QueryValidationSettings..
        /// </summary>
        internal static string NotAllowedQueryOption {
            get {
                return ResourceManager.GetString("NotAllowedQueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null collections cannot be serialized..
        /// </summary>
        internal static string NullCollectionsCannotBeSerialized {
            get {
                return ResourceManager.GetString("NullCollectionsCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections cannot contain null elements..
        /// </summary>
        internal static string NullElementInCollection {
            get {
                return ResourceManager.GetString("NullElementInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function &apos;{0}&apos;..
        /// </summary>
        internal static string ODataFunctionNotSupported {
            get {
                return ResourceManager.GetString("ODataFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData path is invalid..
        /// </summary>
        internal static string ODataPathInvalid {
            get {
                return ResourceManager.GetString("ODataPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be completed because no ODataPath is available for the request..
        /// </summary>
        internal static string ODataPathMissing {
            get {
                return ResourceManager.GetString("ODataPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ordering by properties is supported for non-primitive collections. Expressions are not supported..
        /// </summary>
        internal static string OrderByClauseNotSupported {
            get {
                return ResourceManager.GetString("OrderByClauseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple &apos;$it&apos; nodes are not supported in &apos;$orderby&apos;..
        /// </summary>
        internal static string OrderByDuplicateIt {
            get {
                return ResourceManager.GetString("OrderByDuplicateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property named &apos;{0}&apos; is not supported in &apos;$orderby&apos;..
        /// </summary>
        internal static string OrderByDuplicateProperty {
            get {
                return ResourceManager.GetString("OrderByDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of clauses in $orderby query option exceeded the maximum number allowed. The maximum number of $orderby clauses allowed is {0}..
        /// </summary>
        internal static string OrderByNodeCountExceeded {
            get {
                return ResourceManager.GetString("OrderByNodeCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser requires an EDM model with exactly 1 entity container. {0} entity containers were found..
        /// </summary>
        internal static string ParserModelMustHaveOneContainer {
            get {
                return ResourceManager.GetString("ParserModelMustHaveOneContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous path segment cannot have a null value as its EdmType..
        /// </summary>
        internal static string PreviousSegmentEdmTypeCannotBeNull {
            get {
                return ResourceManager.GetString("PreviousSegmentEdmTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous segment&apos;s EDM type &apos;{0}&apos; must be a collection type..
        /// </summary>
        internal static string PreviousSegmentMustBeCollectionType {
            get {
                return ResourceManager.GetString("PreviousSegmentMustBeCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous segment&apos;s EDM type &apos;{0}&apos; must be a complex type..
        /// </summary>
        internal static string PreviousSegmentMustBeComplexType {
            get {
                return ResourceManager.GetString("PreviousSegmentMustBeComplexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous segment&apos;s EDM type &apos;{0}&apos; must be an entity collection type..
        /// </summary>
        internal static string PreviousSegmentMustBeEntityCollectionType {
            get {
                return ResourceManager.GetString("PreviousSegmentMustBeEntityCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous segment&apos;s EDM type &apos;{0}&apos; must be an entity type..
        /// </summary>
        internal static string PreviousSegmentMustBeEntityType {
            get {
                return ResourceManager.GetString("PreviousSegmentMustBeEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define property &apos;{0}&apos; in the base entity type &apos;{1}&apos; as the derived type &apos;{2}&apos; already defines it..
        /// </summary>
        internal static string PropertyAlreadyDefinedInDerivedType {
            get {
                return ResourceManager.GetString("PropertyAlreadyDefinedInDerivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not belong to the type &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyDoesNotBelongToType {
            get {
                return ResourceManager.GetString("PropertyDoesNotBelongToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; of the property &apos;{1}&apos; on type &apos;{2}&apos; must be a collection..
        /// </summary>
        internal static string PropertyIsNotCollection {
            get {
                return ResourceManager.GetString("PropertyIsNotCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string..
        /// </summary>
        internal static string PropertyMustBeString {
            get {
                return ResourceManager.GetString("PropertyMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string with a length of 1..
        /// </summary>
        internal static string PropertyMustBeStringLengthOne {
            get {
                return ResourceManager.GetString("PropertyMustBeStringLengthOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string with a maximum length of 1..
        /// </summary>
        internal static string PropertyMustBeStringMaxLengthOne {
            get {
                return ResourceManager.GetString("PropertyMustBeStringMaxLengthOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyInfo provided must have public &apos;get&apos; and &apos;set&apos; accessor methods..
        /// </summary>
        internal static string PropertyMustHavePublicGetterAndSetter {
            get {
                return ResourceManager.GetString("PropertyMustHavePublicGetterAndSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM instance of type &apos;{0}&apos; is missing the property &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for OData query &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string QueryCannotBeEmpty {
            get {
                return ResourceManager.GetString("QueryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A model is required for querying. Consider implementing the EnableQueryAttribute.GetModel method never to return a null value..
        /// </summary>
        internal static string QueryGetModelMustNotReturnNull {
            get {
                return ResourceManager.GetString("QueryGetModelMustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries can not be applied to a response content of type &apos;{0}&apos;. The response content must be an ObjectContent..
        /// </summary>
        internal static string QueryingRequiresObjectContent {
            get {
                return ResourceManager.GetString("QueryingRequiresObjectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding OData QueryNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string QueryNodeBindingNotSupported {
            get {
                return ResourceManager.GetString("QueryNodeBindingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating OData QueryNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string QueryNodeValidationNotSupported {
            get {
                return ResourceManager.GetString("QueryNodeValidationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query parameter &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string QueryParameterNotSupported {
            get {
                return ResourceManager.GetString("QueryParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData formatter requires an attached request in order to deserialize. Controller classes must derive from ODataController or be marked with ODataFormattingAttribute. Custom parameter bindings must call GetPerRequestFormatterInstance on each formatter and use these per-request instances..
        /// </summary>
        internal static string ReadFromStreamAsyncMustHaveRequest {
            get {
                return ResourceManager.GetString("ReadFromStreamAsyncMustHaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebinding is not supported..
        /// </summary>
        internal static string RebindingNotSupported {
            get {
                return ResourceManager.GetString("RebindingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complex type &apos;{0}&apos; has a reference to itself through the property &apos;{1}&apos;. A recursive loop of complex types is not allowed..
        /// </summary>
        internal static string RecursiveComplexTypesNotAllowed {
            get {
                return ResourceManager.GetString("RecursiveComplexTypesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request message does not contain an HttpConfiguration object..
        /// </summary>
        internal static string RequestMustContainConfiguration {
            get {
                return ResourceManager.GetString("RequestMustContainConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must have an associated EDM model. Consider using the extension method HttpConfiguration.Routes.MapODataServiceRoute to register a route that parses the OData URI and attaches the model information..
        /// </summary>
        internal static string RequestMustHaveModel {
            get {
                return ResourceManager.GetString("RequestMustHaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must have an associated OData route name. Consider using the extension request.ODataProperties().RouteName to set a route name..
        /// </summary>
        internal static string RequestMustHaveODataRouteName {
            get {
                return ResourceManager.GetString("RequestMustHaveODataRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last segment of the request URI &apos;{0}&apos; was not recognized as an OData action..
        /// </summary>
        internal static string RequestNotActionInvocation {
            get {
                return ResourceManager.GetString("RequestNotActionInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type &apos;{0}&apos; is already declared as an entity type. Use the method &apos;ReturnsCollectionFromEntitySet&apos; if the return type is an entity collection..
        /// </summary>
        internal static string ReturnEntityCollectionWithoutEntitySet {
            get {
                return ResourceManager.GetString("ReturnEntityCollectionWithoutEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type &apos;{0}&apos; is already declared as an entity type. Use the method &apos;ReturnsFromEntitySet&apos; if the return type is an entity..
        /// </summary>
        internal static string ReturnEntityWithoutEntitySet {
            get {
                return ResourceManager.GetString("ReturnEntityWithoutEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;RootElementName&apos; property is required on &apos;{0}&apos;..
        /// </summary>
        internal static string RootElementNameMissing {
            get {
                return ResourceManager.GetString("RootElementNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment value must not be null or empty..
        /// </summary>
        internal static string SegmentNullOrEmpty {
            get {
                return ResourceManager.GetString("SegmentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;select&apos; and &apos;expand&apos; cannot be both null or empty..
        /// </summary>
        internal static string SelectExpandEmptyOrNull {
            get {
                return ResourceManager.GetString("SelectExpandEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $select does not support selections of type &apos;{0}&apos;..
        /// </summary>
        internal static string SelectionTypeNotSupported {
            get {
                return ResourceManager.GetString("SelectionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not an entity type. Only entity types support $select and $expand..
        /// </summary>
        internal static string SelectNonEntity {
            get {
                return ResourceManager.GetString("SelectNonEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; on controller &apos;{1}&apos; returned a {2} containing more than one element. {2} must have zero or one elements..
        /// </summary>
        internal static string SingleResultHasMoreThanOneEntity {
            get {
                return ResourceManager.GetString("SingleResultHasMoreThanOneEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of &apos;{0}&apos; for {1} query has been exceeded. The value from the incoming request is &apos;{2}&apos;..
        /// </summary>
        internal static string SkipTopLimitExceeded {
            get {
                return ResourceManager.GetString("SkipTopLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the target entity type for the navigation property &apos;{0}&apos; on entity type &apos;{1}&apos;..
        /// </summary>
        internal static string TargetEntityTypeMissing {
            get {
                return ResourceManager.GetString("TargetEntityTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be configured as a ComplexType. It was previously configured as an EntityType..
        /// </summary>
        internal static string TypeCannotBeComplexWasEntity {
            get {
                return ResourceManager.GetString("TypeCannotBeComplexWasEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be deserialized using the {1}..
        /// </summary>
        internal static string TypeCannotBeDeserialized {
            get {
                return ResourceManager.GetString("TypeCannotBeDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be configured as an EntityType. It was previously configured as a ComplexType..
        /// </summary>
        internal static string TypeCannotBeEntityWasComplex {
            get {
                return ResourceManager.GetString("TypeCannotBeEntityWasComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be serialized using the {1}..
        /// </summary>
        internal static string TypeCannotBeSerialized {
            get {
                return ResourceManager.GetString("TypeCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not inherit from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeDoesNotInheritFromBaseType {
            get {
                return ResourceManager.GetString("TypeDoesNotInheritFromBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an entity type. Only entity types are supported..
        /// </summary>
        internal static string TypeMustBeEntity {
            get {
                return ResourceManager.GetString("TypeMustBeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a collection of type {1}. Only entity collections are supported..
        /// </summary>
        internal static string TypeMustBeEntityCollection {
            get {
                return ResourceManager.GetString("TypeMustBeEntityCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataMediaTypeFormatter was unable to determine the base URI for the request. The request must be processed by an OData route for the OData formatter to serialize the response..
        /// </summary>
        internal static string UnableToDetermineBaseUrl {
            get {
                return ResourceManager.GetString("UnableToDetermineBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataMediaTypeFormatter must be able to determine the metadata URL for a request in order to serialize the response..
        /// </summary>
        internal static string UnableToDetermineMetadataUrl {
            get {
                return ResourceManager.GetString("UnableToDetermineMetadataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating OData UnaryOperatorNode of kind {0} is not supported by {1}..
        /// </summary>
        internal static string UnaryNodeValidationNotSupported {
            get {
                return ResourceManager.GetString("UnaryNodeValidationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element type &apos;{0}&apos; of the given collection type &apos;{1}&apos; is not of the type &apos;{2}&apos;..
        /// </summary>
        internal static string UnexpectedElementType {
            get {
                return ResourceManager.GetString("UnexpectedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EDM type &apos;{0}&apos; of kind &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedEdmType {
            get {
                return ResourceManager.GetString("UnsupportedEdmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unsupported EdmTypeKind &apos;{0}&apos; in list of available types..
        /// </summary>
        internal static string UnsupportedEdmTypeKind {
            get {
                return ResourceManager.GetString("UnsupportedEdmTypeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Expression NodeType..
        /// </summary>
        internal static string UnsupportedExpressionNodeType {
            get {
                return ResourceManager.GetString("UnsupportedExpressionNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path within the select or expand query option is not supported..
        /// </summary>
        internal static string UnsupportedSelectExpandPath {
            get {
                return ResourceManager.GetString("UnsupportedSelectExpandPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query specified in the URI is not valid. {0}.
        /// </summary>
        internal static string UriQueryStringInvalid {
            get {
                return ResourceManager.GetString("UriQueryStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;Url&apos; of {0} cannot be null..
        /// </summary>
        internal static string UrlHelperNull {
            get {
                return ResourceManager.GetString("UrlHelperNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid. {1}.
        /// </summary>
        internal static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support WriteObjectInline..
        /// </summary>
        internal static string WriteObjectInlineNotSupported {
            get {
                return ResourceManager.GetString("WriteObjectInlineNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support WriteObject..
        /// </summary>
        internal static string WriteObjectNotSupported {
            get {
                return ResourceManager.GetString("WriteObjectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OData formatter does not support writing client requests. This formatter instance must have an associated request..
        /// </summary>
        internal static string WriteToStreamAsyncMustHaveRequest {
            get {
                return ResourceManager.GetString("WriteToStreamAsyncMustHaveRequest", resourceCulture);
            }
        }
    }
}
